// Generated by https://quicktype.io

export interface Invitados {
    id: number;
    fechaLimite: string;
    asunto: string;
    codigo: string;
    limite: number;
    usuario_id: number;
    createdAt: string;
    updatedAt: string;
    deletedAt: null;
    Invitados: Invitado[];
}

export interface Invitado {
    id: number;
    nombre: string;
    apellido: string;
    invitacion_id: number;
    createdAt: string;
    updatedAt: string;
}
