// Generated by https://quicktype.io

export interface Invitacion {
    id: number;
    fechaLimite: string;
    asunto: string;
    codigo: string;
    limite: number;
    usuario_id: number;
    createdAt: string;
    updatedAt: string;
    deletedAt: null;
}
